### ISSUE TITLE
About the displacements

### ISSUE THREAD

**Issue by ChisatoOhyama** [smhaller/perception-neuron-ros#1]
Dear Simon

Greeting,
I really thank you for your doing this project that made perception neuron device work on ROS.
I am starting a project that require the position of my arm and hand now.
However, I tried utilize your program. It  comes out only rotation values but no displacement value in every joint.
Can you explain your correct setup of your configurations of Windows and ROS computer? 

Best Regards,

**Comment by smhaller** [comment]
Dear Chisato,

if i understood you correctly - you already get values to your ROS machine and you can see some output already in tf but the displacement is missing.

could you check on your windows machine in Axis Neuron: the settings for publishing the BVH data: 

File>Settings>Output Format> BVH Data
Freq. reducing: 1
Block Type: Binary 
Rotation: YXZ
with Displacement (selected)
with Reference (selected)

if this does not work please send just a sample output from the rostopic
/perception_neuron/data_1
(rostopic echo /perception_neuron/data_1)

to simon.haller AT uibk.ac.at

best
Simon

**Comment by smhaller** [comment]
Since i didn't get an email, i assume this was the problem.

best
Simon
